import { uid, SIZES, INK, PAPER, RED, MUTE } from './brand';
import { galleryItem } from './gallery';

function text(partial) {
  return {
    id: uid(),
    type: 'text',
    x: 80,
    y: 80,
    w: 400,
    h: 80,
    rotation: 0,
    z: 1,
    content: 'Text',
    fontSize: 32,
    fontWeight: 600,
    fontFamily: 'sans',
    color: INK,
    align: 'left',
    lineHeight: 1.2,
    ...partial,
  };
}

function shape(partial) {
  return {
    id: uid(),
    type: 'shape',
    x: 0,
    y: 0,
    w: 120,
    h: 8,
    rotation: 0,
    z: 1,
    shape: 'rect',
    fill: RED,
    ...partial,
  };
}

function logo(partial) {
  return {
    id: uid(),
    type: 'logo',
    x: 64,
    y: 48,
    w: 360,
    h: 64,
    rotation: 0,
    z: 10,
    inverted: false,
    ...partial,
  };
}

function iconEl(partial) {
  return {
    id: uid(),
    type: 'icon',
    icon: 'check',
    color: INK,
    x: 72,
    y: 72,
    w: 72,
    h: 72,
    rotation: 0,
    z: 4,
    ...partial,
  };
}

function qrEl(partial) {
  return {
    id: uid(),
    type: 'qr',
    value: 'https://tychora.com',
    color: INK,
    bg: PAPER,
    x: 72,
    y: 72,
    w: 160,
    h: 160,
    rotation: 0,
    z: 4,
    ...partial,
  };
}

function imageEl(partial) {
  return {
    id: uid(),
    type: 'image',
    src: '',
    x: 80,
    y: 160,
    w: 480,
    h: 320,
    rotation: 0,
    z: 1,
    fit: 'cover',
    ...partial,
  };
}

export function emptyDesign(size = SIZES[0], name = 'Empty canvas') {
  return {
    id: uid(),
    name,
    updatedAt: Date.now(),
    format: { ...size },
    caption: '',
    hashtags: '',
    background: { type: 'color', value: PAPER },
    elements: [],
  };
}

export function blankDesign(size = SIZES[0], name = 'Untitled post') {
  return {
    id: uid(),
    name,
    updatedAt: Date.now(),
    format: { ...size },
    caption: '',
    hashtags: '',
    background: { type: 'color', value: PAPER },
    elements: [
      logo({ x: 64, y: 48 }),
      text({
        content: 'Write your headline',
        x: 64,
        y: size.h / 2 - 60,
        w: size.w - 128,
        h: 90,
        fontSize: 52,
        fontFamily: 'serif',
        fontWeight: 400,
      }),
    ],
  };
}

function base(sizeId, name, background, elements) {
  const size = SIZES.find((s) => s.id === sizeId) || SIZES[0];
  return {
    id: uid(),
    name,
    updatedAt: Date.now(),
    format: { ...size },
    caption: '',
    hashtags: '',
    background,
    elements,
  };
}

export const TEMPLATES = [
  {
    id: 'ready-software',
    name: 'Ready software',
    blurb: 'LinkedIn landscape',
    sizeId: 'linkedin',
    make: () =>
      base(
        'linkedin',
        'Ready software',
        { type: 'color', value: PAPER },
        [
          logo({ x: 64, y: 48 }),
          shape({ x: 64, y: 140, w: 72, h: 6, z: 2 }),
          text({
            content: 'Software for how\nthe business already runs.',
            x: 64,
            y: 180,
            w: 720,
            h: 220,
            fontSize: 48,
            fontFamily: 'serif',
            fontWeight: 400,
            z: 3,
          }),
          text({
            content: 'CRM · ERP · custom systems  ·  Karachi since 2017',
            x: 64,
            y: 500,
            w: 700,
            h: 40,
            fontSize: 18,
            fontWeight: 500,
            color: MUTE,
            z: 3,
          }),
          shape({ x: 920, y: 0, w: 280, h: 627, fill: INK, z: 1 }),
          text({
            content: 'TYCHORA',
            x: 940,
            y: 280,
            w: 240,
            h: 40,
            fontSize: 14,
            fontWeight: 600,
            color: PAPER,
            align: 'center',
            z: 4,
          }),
          text({
            content: 'hello@tychora.com',
            x: 940,
            y: 330,
            w: 240,
            h: 36,
            fontSize: 13,
            fontWeight: 400,
            color: '#E4E0D8',
            align: 'center',
            z: 4,
          }),
        ]
      ),
  },
  {
    id: 'three-ways',
    name: 'Product · Project · Team',
    blurb: 'Instagram square',
    sizeId: 'instagram',
    make: () =>
      base(
        'instagram',
        'Product · Project · Team',
        { type: 'color', value: INK },
        [
          logo({ x: 72, y: 64, inverted: true, w: 360, h: 64, z: 5 }),
          text({
            content: 'Three ways\nto work with us.',
            x: 72,
            y: 200,
            w: 920,
            h: 200,
            fontSize: 64,
            fontFamily: 'serif',
            color: PAPER,
            z: 3,
          }),
          text({
            content: '01  Product     02  Project     03  Team',
            x: 72,
            y: 820,
            w: 920,
            h: 50,
            fontSize: 22,
            fontWeight: 500,
            color: RED,
            z: 3,
          }),
          text({
            content: 'tychora.com',
            x: 72,
            y: 960,
            w: 400,
            h: 36,
            fontSize: 16,
            color: MUTE,
            z: 3,
          }),
        ]
      ),
  },
  {
    id: 'quote',
    name: 'Quote card',
    blurb: 'Facebook post',
    sizeId: 'facebook',
    make: () =>
      base(
        'facebook',
        'Quote card',
        { type: 'color', value: PAPER },
        [
          shape({ x: 0, y: 0, w: 12, h: 630, fill: RED, z: 2 }),
          text({
            content: '“You talk to the people who ship.”',
            x: 80,
            y: 180,
            w: 1040,
            h: 180,
            fontSize: 52,
            fontFamily: 'serif',
            fontWeight: 400,
            z: 3,
          }),
          text({
            content: 'Tychora Technologies  ·  Karachi, Pakistan and Saudi Arabia',
            x: 80,
            y: 500,
            w: 800,
            h: 40,
            fontSize: 18,
            fontWeight: 500,
            color: MUTE,
            z: 3,
          }),
        ]
      ),
  },
  {
    id: 'crm',
    name: 'CRM highlight',
    blurb: 'LinkedIn square',
    sizeId: 'linkedin-square',
    make: () =>
      base(
        'linkedin-square',
        'CRM highlight',
        { type: 'color', value: PAPER },
        [
          logo({ x: 72, y: 64 }),
          text({
            content: 'CRM',
            x: 72,
            y: 280,
            w: 400,
            h: 50,
            fontSize: 18,
            fontWeight: 600,
            color: RED,
            z: 3,
          }),
          text({
            content: 'Leads, follow-ups,\nand history.\nNot spreadsheets.',
            x: 72,
            y: 360,
            w: 900,
            h: 360,
            fontSize: 56,
            fontFamily: 'serif',
            z: 3,
          }),
          text({
            content: 'Ask if we have a fit  →  hello@tychora.com',
            x: 72,
            y: 940,
            w: 900,
            h: 40,
            fontSize: 20,
            fontWeight: 500,
            color: MUTE,
            z: 3,
          }),
        ]
      ),
  },
  {
    id: 'story-cta',
    name: 'Story CTA',
    blurb: 'Instagram story',
    sizeId: 'story',
    make: () =>
      base(
        'story',
        'Story CTA',
        { type: 'color', value: INK },
        [
          logo({ x: 80, y: 120, inverted: true, w: 340, h: 64, z: 5 }),
          text({
            content: 'Need a CRM,\nERP, or extra\nengineers?',
            x: 80,
            y: 520,
            w: 920,
            h: 480,
            fontSize: 64,
            fontFamily: 'serif',
            color: PAPER,
            z: 3,
          }),
          shape({ x: 80, y: 1100, w: 80, h: 8, fill: RED, z: 3 }),
          text({
            content: 'Write to us.\nWe will say if we are a fit.',
            x: 80,
            y: 1160,
            w: 900,
            h: 120,
            fontSize: 28,
            fontWeight: 400,
            color: '#E4E0D8',
            z: 3,
          }),
          text({
            content: 'hello@tychora.com',
            x: 80,
            y: 1680,
            w: 900,
            h: 50,
            fontSize: 24,
            fontWeight: 600,
            color: RED,
            z: 3,
          }),
        ]
      ),
  },
  {
    id: 'hiring',
    name: 'Staff augmentation',
    blurb: 'X / Twitter',
    sizeId: 'x',
    make: () =>
      base(
        'x',
        'Staff augmentation',
        { type: 'color', value: PAPER },
        [
          logo({ x: 72, y: 56 }),
          text({
            content: 'Add our engineers to your team.',
            x: 72,
            y: 280,
            w: 1100,
            h: 140,
            fontSize: 56,
            fontFamily: 'serif',
            z: 3,
          }),
          text({
            content: 'Extra hands. Not a whole new vendor. Compact team — we take work we can actually staff.',
            x: 72,
            y: 480,
            w: 1000,
            h: 90,
            fontSize: 24,
            fontWeight: 400,
            color: MUTE,
            z: 3,
          }),
          text({
            content: 'tychora.com',
            x: 72,
            y: 780,
            w: 400,
            h: 40,
            fontSize: 18,
            fontWeight: 600,
            color: RED,
            z: 3,
          }),
        ]
      ),
  },
  {
    id: 'event',
    name: 'Announcement',
    blurb: 'LinkedIn landscape',
    sizeId: 'linkedin',
    make: () =>
      base(
        'linkedin',
        'Announcement',
        { type: 'color', value: INK },
        [
          text({
            content: 'ANNOUNCEMENT',
            x: 72,
            y: 80,
            w: 400,
            h: 36,
            fontSize: 14,
            fontWeight: 600,
            color: RED,
            z: 3,
          }),
          text({
            content: 'Tell us the problem.\nWe say if we are a fit.',
            x: 72,
            y: 180,
            w: 900,
            h: 220,
            fontSize: 48,
            fontFamily: 'serif',
            color: PAPER,
            z: 3,
          }),
          text({
            content: 'Product, project, or extra engineers. Karachi · Pakistan and Saudi Arabia.',
            x: 72,
            y: 480,
            w: 800,
            h: 50,
            fontSize: 20,
            color: MUTE,
            z: 3,
          }),
        ]
      ),
  },
  {
    id: 'photo-frame',
    name: 'Photo frame',
    blurb: 'Instagram — drop in a photo',
    sizeId: 'instagram',
    make: () =>
      base(
        'instagram',
        'Photo frame',
        { type: 'color', value: INK },
        [
          shape({ x: 72, y: 180, w: 936, h: 700, fill: '#1C2026', z: 1 }),
          text({
            content: 'Replace this block with your photo',
            x: 72,
            y: 480,
            w: 936,
            h: 50,
            fontSize: 22,
            fontWeight: 500,
            color: MUTE,
            align: 'center',
            z: 2,
          }),
          logo({ x: 72, y: 64, inverted: true, z: 5 }),
          text({
            content: 'Tychora  ·  tychora.com',
            x: 72,
            y: 960,
            w: 900,
            h: 40,
            fontSize: 18,
            fontWeight: 500,
            color: PAPER,
            z: 3,
          }),
        ]
      ),
  },
  {
    id: 'erp',
    name: 'ERP highlight',
    blurb: 'Instagram portrait',
    sizeId: 'ig-portrait',
    make: () =>
      base(
        'ig-portrait',
        'ERP highlight',
        { type: 'color', value: PAPER },
        [
          logo({ x: 72, y: 64 }),
          text({
            content: 'ERP',
            x: 72,
            y: 280,
            w: 400,
            h: 40,
            fontSize: 16,
            fontWeight: 600,
            color: RED,
            z: 3,
          }),
          text({
            content: 'Stock, purchasing,\nand finance.\nSame numbers.',
            x: 72,
            y: 360,
            w: 920,
            h: 420,
            fontSize: 56,
            fontFamily: 'serif',
            z: 3,
          }),
          shape({ x: 72, y: 860, w: 64, h: 6, z: 3 }),
          text({
            content: 'hello@tychora.com',
            x: 72,
            y: 1180,
            w: 800,
            h: 40,
            fontSize: 22,
            fontWeight: 600,
            z: 3,
          }),
        ]
      ),
  },
  {
    id: 'banner',
    name: 'LinkedIn banner',
    blurb: 'Profile cover',
    sizeId: 'linkedin-cover',
    make: () =>
      base(
        'linkedin-cover',
        'LinkedIn banner',
        { type: 'color', value: INK },
        [
          logo({ x: 64, y: 40, inverted: true, z: 5 }),
          text({
            content: 'Ready software. Custom builds. Engineers on your team.',
            x: 64,
            y: 160,
            w: 1100,
            h: 90,
            fontSize: 36,
            fontFamily: 'serif',
            color: PAPER,
            z: 3,
          }),
          text({
            content: 'tychora.com',
            x: 64,
            y: 300,
            w: 400,
            h: 36,
            fontSize: 18,
            fontWeight: 600,
            color: RED,
            z: 3,
          }),
        ]
      ),
  },
  {
    id: 'testimonial',
    name: 'Proof line',
    blurb: 'Facebook post',
    sizeId: 'facebook',
    make: () =>
      base(
        'facebook',
        'Proof line',
        { type: 'color', value: PAPER },
        [
          logo({ x: 72, y: 48 }),
          text({
            content: 'A compact Karachi office.\nYou talk to the people who ship.',
            x: 72,
            y: 200,
            w: 1050,
            h: 200,
            fontSize: 42,
            fontFamily: 'serif',
            z: 3,
          }),
          text({
            content: 'Since 2017  ·  Pakistan and Saudi Arabia',
            x: 72,
            y: 500,
            w: 700,
            h: 40,
            fontSize: 18,
            color: MUTE,
            z: 3,
          }),
        ]
      ),
  },
  {
    id: 'hiring-team',
    name: 'Hiring / team',
    blurb: 'LinkedIn square',
    sizeId: 'linkedin-square',
    make: () =>
      base(
        'linkedin-square',
        'Hiring / team',
        { type: 'color', value: INK },
        [
          logo({ x: 72, y: 64, inverted: true, w: 360, h: 64, z: 5 }),
          iconEl({ icon: 'users', color: RED, x: 72, y: 220, w: 64, h: 64, z: 4 }),
          text({
            content: 'Need extra engineers,\nnot a whole new vendor?',
            x: 72,
            y: 320,
            w: 920,
            h: 240,
            fontSize: 52,
            fontFamily: 'serif',
            color: PAPER,
            z: 3,
          }),
          text({
            content: 'Add our team to yours. Compact. We take the work we can actually staff.',
            x: 72,
            y: 620,
            w: 900,
            h: 120,
            fontSize: 24,
            fontWeight: 400,
            color: MUTE,
            z: 3,
          }),
          text({
            content: 'tychora.com',
            x: 72,
            y: 960,
            w: 400,
            h: 36,
            fontSize: 18,
            fontWeight: 600,
            color: RED,
            z: 3,
          }),
        ]
      ),
  },
  {
    id: 'client-quote',
    name: 'Client quote',
    blurb: 'Facebook post',
    sizeId: 'facebook',
    make: () =>
      base(
        'facebook',
        'Client quote',
        { type: 'color', value: PAPER },
        [
          logo({ x: 72, y: 40 }),
          text({
            content: '“',
            x: 64,
            y: 108,
            w: 120,
            h: 80,
            fontSize: 88,
            fontFamily: 'serif',
            color: RED,
            z: 3,
          }),
          text({
            content: 'They sat with how we already work. Then they built the system around that.',
            x: 72,
            y: 210,
            w: 780,
            h: 200,
            fontSize: 34,
            fontFamily: 'serif',
            z: 3,
          }),
          imageEl({
            src: galleryItem('talk').src,
            x: 920,
            y: 160,
            w: 200,
            h: 200,
            radius: 999,
            z: 2,
          }),
          text({
            content: 'Sara Ahmed',
            x: 72,
            y: 470,
            w: 700,
            h: 36,
            fontSize: 20,
            fontWeight: 600,
            z: 3,
          }),
          text({
            content: 'Operations lead  ·  Karachi',
            x: 72,
            y: 512,
            w: 700,
            h: 32,
            fontSize: 16,
            color: MUTE,
            z: 3,
          }),
        ]
      ),
  },
  {
    id: 'event-cta',
    name: 'Write to us',
    blurb: 'LinkedIn landscape · QR',
    sizeId: 'linkedin',
    make: () =>
      base(
        'linkedin',
        'Write to us',
        { type: 'color', value: PAPER },
        [
          logo({ x: 64, y: 48 }),
          shape({ x: 64, y: 140, w: 72, h: 6, z: 2 }),
          text({
            content: 'Tell us the problem.\nWe say if we are a fit.',
            x: 64,
            y: 180,
            w: 740,
            h: 200,
            fontSize: 42,
            fontFamily: 'serif',
            z: 3,
          }),
          text({
            content: 'hello@tychora.com',
            x: 64,
            y: 430,
            w: 500,
            h: 40,
            fontSize: 22,
            fontWeight: 600,
            z: 3,
          }),
          text({
            content: 'Scan for tychora.com',
            x: 64,
            y: 530,
            w: 400,
            h: 32,
            fontSize: 16,
            color: MUTE,
            z: 3,
          }),
          qrEl({ x: 980, y: 200, w: 160, h: 160, z: 4 }),
        ]
      ),
  },
  {
    id: 'were-hiring',
    name: "We're hiring",
    blurb: 'LinkedIn square · people',
    sizeId: 'linkedin-square',
    make: () =>
      base(
        'linkedin-square',
        "We're hiring",
        { type: 'color', value: PAPER },
        [
          logo({ x: 72, y: 64 }),
          iconEl({ icon: 'megaphone', color: RED, x: 72, y: 200, w: 72, h: 72, z: 4 }),
          text({
            content: 'WE’RE HIRING',
            x: 72,
            y: 300,
            w: 500,
            h: 36,
            fontSize: 16,
            fontWeight: 600,
            color: RED,
            z: 3,
          }),
          text({
            content: 'Join the people\nwho ship.',
            x: 72,
            y: 360,
            w: 920,
            h: 220,
            fontSize: 64,
            fontFamily: 'serif',
            z: 3,
          }),
          text({
            content: 'A compact Karachi office. You work next to the people who talk to the client — not a floor of account managers.',
            x: 72,
            y: 640,
            w: 900,
            h: 140,
            fontSize: 24,
            fontWeight: 400,
            color: MUTE,
            z: 3,
          }),
          iconEl({ icon: 'user-plus', color: INK, x: 72, y: 860, w: 40, h: 40, z: 4 }),
          text({
            content: 'Open roles  →  hello@tychora.com',
            x: 128,
            y: 864,
            w: 800,
            h: 40,
            fontSize: 22,
            fontWeight: 500,
            z: 3,
          }),
          text({
            content: 'hello@tychora.com   ·   Karachi',
            x: 72,
            y: 980,
            w: 800,
            h: 36,
            fontSize: 16,
            color: MUTE,
            z: 3,
          }),
        ]
      ),
  },
  {
    id: 'vacancy',
    name: 'Open role / vacancy',
    blurb: 'LinkedIn landscape',
    sizeId: 'linkedin',
    make: () =>
      base(
        'linkedin',
        'Open role / vacancy',
        { type: 'color', value: PAPER },
        [
          logo({ x: 64, y: 40 }),
          shape({ x: 64, y: 120, w: 72, h: 6, z: 2 }),
          text({
            content: 'OPEN ROLE',
            x: 64,
            y: 150,
            w: 400,
            h: 32,
            fontSize: 14,
            fontWeight: 600,
            color: RED,
            z: 3,
          }),
          text({
            content: 'Software engineer',
            x: 64,
            y: 200,
            w: 720,
            h: 90,
            fontSize: 48,
            fontFamily: 'serif',
            z: 3,
          }),
          text({
            content: 'CRM, ERP, and custom systems. Small team. Karachi office. You talk to the people who ship.',
            x: 64,
            y: 320,
            w: 700,
            h: 100,
            fontSize: 20,
            fontWeight: 400,
            color: MUTE,
            z: 3,
          }),
          text({
            content: 'Karachi  ·  Full-time  ·  hello@tychora.com',
            x: 64,
            y: 520,
            w: 700,
            h: 36,
            fontSize: 18,
            fontWeight: 600,
            z: 3,
          }),
          iconEl({ icon: 'users', color: RED, x: 980, y: 220, w: 120, h: 120, badge: true, badgeFill: INK, badgeInk: PAPER, z: 4 }),
        ]
      ),
  },
  {
    id: 'vacancy-carousel',
    name: 'Vacancy — 3 slides',
    blurb: 'LinkedIn carousel · hiring',
    sizeId: 'linkedin-square',
    make: () => makeVacancyCarousel(),
  },
  {
    id: 'event-invite',
    name: 'Event / invite',
    blurb: 'LinkedIn landscape',
    sizeId: 'linkedin',
    make: () =>
      base(
        'linkedin',
        'Event / invite',
        { type: 'color', value: PAPER },
        [
          logo({ x: 64, y: 40 }),
          iconEl({ icon: 'calendar', color: RED, x: 64, y: 140, w: 56, h: 56, z: 4 }),
          text({
            content: 'EVENT',
            x: 136,
            y: 152,
            w: 300,
            h: 32,
            fontSize: 14,
            fontWeight: 600,
            color: RED,
            z: 3,
          }),
          text({
            content: 'Office hours.\nBring the problem.',
            x: 64,
            y: 220,
            w: 700,
            h: 160,
            fontSize: 42,
            fontFamily: 'serif',
            z: 3,
          }),
          text({
            content: 'Thursday  ·  4pm  ·  Karachi office\nWrite to hello@tychora.com',
            x: 64,
            y: 420,
            w: 700,
            h: 80,
            fontSize: 18,
            color: MUTE,
            z: 3,
          }),
          imageEl({
            src: galleryItem('meeting').src,
            x: 820,
            y: 80,
            w: 340,
            h: 467,
            z: 2,
          }),
        ]
      ),
  },
  {
    id: 'welcome-joiner',
    name: 'Welcome / onboard',
    blurb: 'LinkedIn square · people',
    sizeId: 'linkedin-square',
    make: () =>
      base(
        'linkedin-square',
        'Welcome / onboard',
        { type: 'color', value: INK },
        [
          logo({ x: 72, y: 64, inverted: true, z: 5 }),
          imageEl({
            src: galleryItem('portrait').src,
            x: 72,
            y: 200,
            w: 360,
            h: 480,
            z: 2,
          }),
          text({
            content: 'WELCOME',
            x: 460,
            y: 220,
            w: 540,
            h: 32,
            fontSize: 14,
            fontWeight: 600,
            color: RED,
            z: 3,
          }),
          text({
            content: 'Meet Ayesha.\nEngineer.',
            x: 460,
            y: 280,
            w: 540,
            h: 200,
            fontSize: 48,
            fontFamily: 'serif',
            color: PAPER,
            z: 3,
          }),
          text({
            content: 'First week on the team that ships.',
            x: 460,
            y: 520,
            w: 540,
            h: 140,
            fontSize: 20,
            color: MUTE,
            z: 3,
          }),
          text({
            content: 'tychora.com',
            x: 72,
            y: 980,
            w: 400,
            h: 36,
            fontSize: 16,
            fontWeight: 600,
            color: RED,
            z: 3,
          }),
        ]
      ),
  },
  {
    id: 'photo-post',
    name: 'Photo post',
    blurb: 'Instagram square · gallery',
    sizeId: 'instagram',
    make: () =>
      base(
        'instagram',
        'Photo post',
        { type: 'color', value: INK },
        [
          imageEl({ src: galleryItem('office').src, x: 0, y: 0, w: 1080, h: 1080, z: 1, overlay: '#12151A', overlayOpacity: 0.28 }),
          logo({ x: 72, y: 64, inverted: true, z: 5 }),
          text({
            content: 'A compact\nKarachi office.',
            x: 72,
            y: 720,
            w: 900,
            h: 180,
            fontSize: 52,
            fontFamily: 'serif',
            color: PAPER,
            shadow: true,
            z: 3,
          }),
          text({
            content: 'You talk to the people who ship.',
            x: 72,
            y: 940,
            w: 800,
            h: 40,
            fontSize: 20,
            color: PAPER,
            z: 3,
          }),
        ]
      ),
  },
  {
    id: 'onboard-carousel',
    name: 'Onboard — 3 slides',
    blurb: 'LinkedIn carousel · new joiner',
    sizeId: 'linkedin-square',
    make: () => makeOnboardCarousel(),
  },
  {
    id: 'crm-before-after',
    name: 'CRM before / after',
    blurb: 'LinkedIn carousel · 2 slides',
    sizeId: 'linkedin-square',
    make: () => makeCrmBeforeAfter(),
  },
  {
    id: 'ways-carousel',
    name: 'Ways to work — 3 slides',
    blurb: 'LinkedIn carousel',
    sizeId: 'linkedin-square',
    make: () => makeWaysCarousel(),
  },
];

export function makeWaysCarousel() {
  const size = SIZES.find((s) => s.id === 'linkedin-square') || SIZES[1];
  const cards = [
    { n: '01', title: 'Product', line: 'Prepaid and ready systems we can implement for how your team already works.' },
    { n: '02', title: 'Project', line: 'New CRM, ERP, or custom software when a product is not enough.' },
    { n: '03', title: 'Team', line: 'Add our engineers to yours. Extra hands, not a whole new vendor.' },
  ];
  const slides = cards.map((card, i) => {
    const dark = i === 1;
    return {
      id: uid(),
      background: { type: 'color', value: dark ? INK : PAPER },
      elements: [
        logo({ x: 72, y: 64, inverted: dark, z: 5 }),
        text({ content: card.n, x: 72, y: 260, w: 200, h: 40, fontSize: 18, fontWeight: 600, color: RED, z: 3 }),
        text({
          content: card.title,
          x: 72,
          y: 320,
          w: 900,
          h: 90,
          fontSize: 64,
          fontFamily: 'serif',
          color: dark ? PAPER : INK,
          z: 3,
        }),
        text({
          content: card.line,
          x: 72,
          y: 460,
          w: 900,
          h: 180,
          fontSize: 28,
          fontWeight: 400,
          color: MUTE,
          z: 3,
        }),
        text({
          content: `${i + 1} / 3   ·   tychora.com`,
          x: 72,
          y: 980,
          w: 800,
          h: 36,
          fontSize: 16,
          color: MUTE,
          z: 3,
        }),
      ],
    };
  });
  return {
    id: uid(),
    name: 'Ways to work — carousel',
    updatedAt: Date.now(),
    format: { ...size },
    caption: 'Three ways to work with us.\n\n01 Product — ready software.\n02 Project — built for you.\n03 Team — engineers on your team.\n\nWrite to us. We will say if we are a fit.\nhello@tychora.com',
    hashtags: '#Tychora #Product #Project #Team #Karachi',
    slideIndex: 0,
    slides,
    background: slides[0].background,
    elements: slides[0].elements,
  };
}

export function makeCrmBeforeAfter() {
  const size = SIZES.find((s) => s.id === 'linkedin-square') || SIZES[1];
  const cards = [
    {
      dark: false,
      kicker: 'Before',
      title: 'Follow-ups live\nin a spreadsheet.',
      line: 'Who called, what was said, and when to next — split across chats and files.',
    },
    {
      dark: true,
      kicker: 'After',
      title: 'History sits\non the lead.',
      line: 'The next person who opens the record can see what happened. That is the CRM.',
    },
  ];
  const slides = cards.map((card, i) => ({
    id: uid(),
    background: { type: 'color', value: card.dark ? INK : PAPER },
    elements: [
      logo({ x: 72, y: 64, inverted: card.dark, z: 5 }),
      text({ content: card.kicker, x: 72, y: 240, w: 300, h: 40, fontSize: 18, fontWeight: 600, color: RED, z: 3 }),
      text({
        content: card.title,
        x: 72,
        y: 300,
        w: 920,
        h: 220,
        fontSize: 56,
        fontFamily: 'serif',
        color: card.dark ? PAPER : INK,
        z: 3,
      }),
      text({
        content: card.line,
        x: 72,
        y: 560,
        w: 900,
        h: 160,
        fontSize: 26,
        fontWeight: 400,
        color: MUTE,
        z: 3,
      }),
      text({
        content: `${i + 1} / 2   ·   tychora.com`,
        x: 72,
        y: 980,
        w: 800,
        h: 36,
        fontSize: 16,
        color: MUTE,
        z: 3,
      }),
    ],
  }));
  return {
    id: uid(),
    name: 'CRM before / after',
    updatedAt: Date.now(),
    format: { ...size },
    caption: 'Before: follow-ups in a spreadsheet.\nAfter: history on the lead.\n\nThat is the CRM. Ask if we have a fit.\nhello@tychora.com',
    hashtags: '#Tychora #CRM #Karachi',
    slideIndex: 0,
    slides,
    background: slides[0].background,
    elements: slides[0].elements,
  };
}

export function makeVacancyCarousel() {
  const size = SIZES.find((s) => s.id === 'linkedin-square') || SIZES[1];
  const cards = [
    {
      dark: false,
      icon: 'megaphone',
      kicker: '01  Role',
      title: 'Software\nengineer',
      line: 'CRM, ERP, and custom systems. Karachi. Full-time. hello@tychora.com',
    },
    {
      dark: true,
      icon: 'users',
      kicker: '02  The team',
      title: 'A compact office.\nPeople who ship.',
      line: 'You sit with the people who talk to the client. Not a floor of account managers.',
    },
    {
      dark: false,
      icon: 'send',
      kicker: '03  Apply',
      title: 'Write to us.',
      line: 'A short note and a CV. We will say if there is a fit.\nhello@tychora.com',
    },
  ];
  const slides = cards.map((card, i) => ({
    id: uid(),
    background: { type: 'color', value: card.dark ? INK : PAPER },
    elements: [
      logo({ x: 72, y: 64, inverted: card.dark, z: 5 }),
      iconEl({ icon: card.icon, color: RED, x: 72, y: 200, w: 64, h: 64, z: 4 }),
      text({ content: card.kicker, x: 72, y: 290, w: 400, h: 36, fontSize: 18, fontWeight: 600, color: RED, z: 3 }),
      text({
        content: card.title,
        x: 72,
        y: 350,
        w: 920,
        h: 220,
        fontSize: 56,
        fontFamily: 'serif',
        color: card.dark ? PAPER : INK,
        z: 3,
      }),
      text({
        content: card.line,
        x: 72,
        y: 620,
        w: 900,
        h: 180,
        fontSize: 26,
        fontWeight: 400,
        color: MUTE,
        z: 3,
      }),
      text({
        content: `${i + 1} / 3   ·   tychora.com`,
        x: 72,
        y: 980,
        w: 800,
        h: 36,
        fontSize: 16,
        color: MUTE,
        z: 3,
      }),
    ],
  }));
  return {
    id: uid(),
    name: 'Vacancy — 3 slides',
    updatedAt: Date.now(),
    format: { ...size },
    caption: 'We are hiring a software engineer.\n\nKarachi. Small team. CRM, ERP, and custom systems.\n\nWrite to us — a short note and a CV.\nhello@tychora.com',
    hashtags: '#Tychora #Hiring #Karachi #SoftwareEngineer',
    slideIndex: 0,
    slides,
    background: slides[0].background,
    elements: slides[0].elements,
  };
}

export function makeOnboardCarousel() {
  const size = SIZES.find((s) => s.id === 'linkedin-square') || SIZES[1];
  const cards = [
    {
      dark: false,
      icon: 'user-plus',
      kicker: '01  Welcome',
      title: 'You are on\nthe team.',
      line: 'Ayesha joins as an engineer. A compact Karachi office. You sit with the people who ship.',
    },
    {
      dark: true,
      icon: 'layers',
      kicker: '02  How we work',
      title: 'Product.\nProject. Team.',
      line: 'Ready software, a build, or extra engineers. We take the work we can actually staff.',
    },
    {
      dark: false,
      icon: 'send',
      kicker: '03  First week',
      title: 'Ask.\nThen ship.',
      line: 'Write to the person who hired you. Hello is hello@tychora.com if you are stuck.',
    },
  ];
  const slides = cards.map((card, i) => ({
    id: uid(),
    background: { type: 'color', value: card.dark ? INK : PAPER },
    elements: [
      logo({ x: 72, y: 64, inverted: card.dark, z: 5 }),
      iconEl({ icon: card.icon, color: RED, x: 72, y: 200, w: 64, h: 64, z: 4 }),
      text({ content: card.kicker, x: 72, y: 290, w: 500, h: 36, fontSize: 18, fontWeight: 600, color: RED, z: 3 }),
      text({
        content: card.title,
        x: 72,
        y: 350,
        w: 920,
        h: 220,
        fontSize: 56,
        fontFamily: 'serif',
        color: card.dark ? PAPER : INK,
        z: 3,
      }),
      text({
        content: card.line,
        x: 72,
        y: 620,
        w: 900,
        h: 180,
        fontSize: 26,
        fontWeight: 400,
        color: MUTE,
        z: 3,
      }),
      text({
        content: `${i + 1} / 3   ·   tychora.com`,
        x: 72,
        y: 980,
        w: 800,
        h: 36,
        fontSize: 16,
        color: MUTE,
        z: 3,
      }),
    ],
  }));
  return {
    id: uid(),
    name: 'Onboard — 3 slides',
    updatedAt: Date.now(),
    format: { ...size },
    caption: 'Welcome to the team.\n\nA compact Karachi office. You sit with the people who ship.\n\ntychora.com',
    hashtags: '#Tychora #Team #Karachi',
    slideIndex: 0,
    slides,
    background: slides[0].background,
    elements: slides[0].elements,
  };
}
